import Banner from "@/components/Banner";
import List from "@/components/list";
import Head from "next/head";
import { useState, useEffect } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>beer ideas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/reddit.ico" />
      </Head>
      <main className="container">
        <Banner />
        <List />
      </main>
    </>
  );
}
