import CommentList from "@/components/CommentList";
import Post from "@/components/Post";
import Head from "next/head";
import { useState, useEffect } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>beer ideas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/reddit.ico" />
      </Head>
      <main className="container my-4 px-4">
        <Post />
        <CommentList />
      </main>
    </>
  );
}
